### ISSUE TITLE
Sytanx sugar for automatically finding the return type in @abstract

### ISSUE THREAD

**Issue by MasonProtter** [MikeInnes/Mjolnir.jl#10]
Just playing around with this, I find myself writing the following a lot:
```julia
@abstract Basic f(x::T) where {T} = Core.Compiler.return_type(f, Tuple{T})
```
It might be nice if we just made 
```julia
@abstract Basic f(x)
```
lower to the above.

**Comment by MikeInnes** [comment]
Does `@pure Basic f` do what you want?

**Comment by MasonProtter** [comment]
Ah, I see yes it does. I glanced at it before and assumed it was somehow related to `Base.@pure`. Out of curiosity, why the name `@pure` for this?

**Comment by MikeInnes** [comment]
`@pure` does actually assume purity, i.e. if `f` is called with constants it'll just evaluate the function directly while tracing. So that may or may not be the behaviour you want.

So far for the few non-pure functions I've needed to add (e.g. `println`, `rand`), it's been quite easy to specify the return type directly. It can be a good idea to avoid `return_type` where possible as it can be slow.

**Comment by MasonProtter** [comment]
Thanks, Mike. This is a really amazing piece of work.
